version: '3'

services:
  client:
    build: ./client
    command: npm start
    volumes:
    - ./client/dist:/home/node/app/dist
    - ./client/src:/home/node/app/src
    - ./client/.babelrc:/home/node/app/.babelrc
    - ./client/Dockerfile:/home/node/app/Dockerfile
    - ./client/package.json:/home/node/app/package.json
    - ./client/package-lock.json:/home/node/app/package-lock.json
    ports:
      - 1234:1234
      - 8080:8080
    depends_on:
      - api

  api:
    container_name: crosswalk_api
    build:
      context: api
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/home/python/api
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=apidb
    depends_on:
      - apidb

  apidb:
    container_name: crosswalk_apidb
    image: mongo:4.4.5


  messagesapi:
    container_name: crosswalk_messagesapi
    build:
      context: messagesapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./messagesapi:/home/python/messagesapi
    ports:
      - 8100:8000
    environment:
      - DATABASE_HOST=messagesdb
    depends_on:
      - messagesdb

  messagesdb:
    container_name: crosswalk_messagesdb
    image: mongo:4.4.5

  reactionsapi:
    container_name: crosswalk_reactionsapi
    build:
      context: reactionsapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
    - ./reactionsapi:/home/python/reactionsapi
    ports:
    - 8200:8000
    environment:
      - DATABASE_HOST=reactionsdb
    depends_on:
      - reactionsdb

  reactionsdb:
    container_name: crosswalk_reactionsdb
    image: mongo:4.4.5