version: '3'
services:
  events:
    container_name: crosswalk_events
    build:
      context: events
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./events:/home/python/events
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=eventsdb
    depends_on:
      - eventsdb

  eventsdb:
    container_name: crosswalk_eventsdb
    image: mongo:4.4.5


  messagesapi:
    container_name: crosswalk_messagesapi
    build:
      context: messagesapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./messagesapi:/home/python/messagesapi
    ports:
      - 8100:8000
    environment:
      - DATABASE_HOST=messagesdb
    depends_on:
      - messagesdb

  messagesdb:
    container_name: crosswalk_messagesdb
    image: mongo:4.4.5

  reactionsapi:
    container_name: crosswalk_reactionsapi
    build:
      context: reactionsapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
    - ./reactionsapi:/home/python/reactionsapi
    ports:
    - 8200:8000
    environment:
      - DATABASE_HOST=reactionsdb
    depends_on:
      - reactionsdb

  reactionsdb:
    container_name: crosswalk_reactionsdb
    image: mongo:4.4.5