version: '3'

services:
  client:
    build: ./client
    command: npm start
    volumes:
    - ./client/dist:/home/node/app/dist
    - ./client/src:/home/node/app/src
    - ./client/.babelrc:/home/node/app/.babelrc
    - ./client/Dockerfile:/home/node/app/Dockerfile
    - ./client/package.json:/home/node/app/package.json
    - ./client/package-lock.json:/home/node/app/package-lock.json
    ports:
      - 1234:1234
      - 8080:8080
    depends_on:
      - api

  api:
    build:
      context: api
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/home/python/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    env_file:
      - api/.env
    depends_on:
      - apidb
      - kafka

  apidb:
    image: mongo:4.4.5

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    env_file:
      - kafka/.env
    depends_on:
      - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
