version: '3'
services:
  eventsapi:
    container_name: crosswalk_eventsapi
    build:
      context: eventsapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./eventsapi:/home/python/eventsapi
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOST=eventsdb
    depends_on:
      - eventsdb

  eventsdb:
    container_name: crosswalk_eventsdb
    image: mongo:4.4.5


  messagesapi:
    container_name: crosswalk_messagesapi
    build:
      context: messagesapi
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./messagesapi:/home/python/messagesapi
    ports:
      - 9000:8000
    environment:
      - DATABASE_HOST=messagesdb
    depends_on:
      - messagesdb

  messagesdb:
    container_name: crosswalk_messagesdb
    image: mongo:4.4.5